apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pb0fervxm-nodejs 
  janus-idp.io/tekton: pb0fervxm-nodejs
  backstage.io/kubernetes-id: pb0fervxm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pb0fervxm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  