apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pb0fervxm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pb0fervxm-nodejs 
  name: pb0fervxm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pb0fervxm-nodejs 
